sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t jmooney5000/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jmooney5000/docker-react npm run test